name: Gradle Package CAS
env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server"
  GRADLE_BUILD_OPTIONS: "--no-daemon -x check -x test -x javadoc --configure-on-demand --max-workers=8 --no-configuration-cache"
  TERM: xterm-256color
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GRADLE_BUILDCACHE_USER: ci
  GRADLE_BUILDCACHE_PSW: ${{ secrets.GRADLE_BUILDCACHE_PSW }}
  GH_PACKAGE_REGISTRY_USER: ${{ secrets.GH_PACKAGE_REGISTRY_USER }}
  GH_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GH_PACKAGE_REGISTRY_TOKEN }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  JDK_CURRENT: 11
  JDK_LATEST: 11
  JDK_DISTRIBUTION: "temurin"
 
on: workflow_dispatch
# release:
#   types: [created]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ env.JDK_CURRENT }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JDK_CURRENT }}
        distribution: ${{ env.JDK_DISTRIBUTION }}
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
 
    - name: Build with Gradle
      #run: ./gradlew clean build ${{ env.GRADLE_BUILD_OPTIONS }}
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
 
    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish
      #run: ./gradlew publish
      env:
        USERNAME: "AndyNikolaev"
        #USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
